name = "dud"
main = "src/index.ts"
compatibility_date = "2026-04-19"
workers_dev = false

[vars]
APP_VERSION = "1.1.0"

[[routes]]
pattern = "dud.example.com"
custom_domain = true

[[r2_buckets]]
binding = "FILES"
bucket_name = "dud-files"
