// SPDX-License-Identifier: MIT
// Copyright (C) 2026 Wojciech Polak

// Independent verification of the frozen wire corpus generated by the Go
// client (client/cmd/dud/v2_vectors_test.go). The server decoders must accept
// exactly the vectors the client produces and reject exactly the ones it marks
// invalid, so both implementations stay pinned to the same bytes.

import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

import { decodeCbor, encodeCbor } from '../dist/src/cbor.js';
import {
  buildV2DeliveryProof,
  deriveV2DailyCapabilityLookupId,
  deriveV2EnrollmentKey,
  deriveV2EnrollmentProof,
  hexToBytes,
  parseV2DeliveryProof,
  V2_ENROLLMENT_KDF_ITERATIONS,
  verifyV2DeliveryProof,
} from '../dist/src/v2-auth.js';
import { sha256 } from '../dist/src/sha256.js';
import {
  decodeV2ControlEventRequest,
  decodeV2CompletionRequest,
  decodeV2DeliveryRequestFrame,
  decodeV2InboxRequest,
  decodeV2InboxResponseFrame,
  encodeV2DeliveryFrame,
  v2CompletionRequestAuthorizationDigest,
  v2ControlEventRequestAuthorizationDigest,
  v2DeliveryFrameAuthorizationDigest,
  v2InboxRequestAuthorizationDigest,
  V2_COMPLETION_REQUEST_KEYS,
  V2_CONTROL_EVENT_REQUEST_KEYS,
  V2_DELIVERY_REQUEST_KEYS,
  V2_INBOX_REQUEST_KEYS,
  V2_MAX_BATCHED_SLOT_PROOFS,
  V2_MAX_ENCRYPTED_DESCRIPTOR_BYTES,
} from '../dist/src/v2-delivery-frame.js';

const corpus = JSON.parse(
  readFileSync(new URL('./vectors/v2-wire-vectors.json', import.meta.url)),
);

function bytes(hex) {
  return hexToBytes(hex);
}

function hex(value) {
  return Array.from(value, (byte) => byte.toString(16).padStart(2, '0')).join(
    '',
  );
}

/**
 * Rejection reasons keyed by the corpus category. Each implementation keeps its
 * own patterns so a vector cannot pass by being refused for an unrelated fault.
 */
const REJECTION = {
  'frame-magic': /magic/,
  'frame-prefix': /prefix/,
  'frame-header-length': /header length/,
  'payload-digest': /digest does not match/,
  'payload-length': /length does not match/,
  'non-deterministic-cbor': /minimally|deterministic|truncated/,
  'unknown-header-key': /unknown core key/,
  'missing-required-key': /missing required key|slot proofs are invalid/i,
  'field-length': /is invalid|are invalid/,
  'descriptor-bounds': /descriptor exceeds the configured limit/,
  'acknowledgement-bounds': /acknowledgement exceeds the configured limit/,
  'envelope-bounds': /envelope exceeds the configured limit/,
  'policy-shape': /policy is invalid/,
  'batch-limit': /invalid|configured limit/,
  'result-range': /result is invalid/,
  'orphan-delivery-field': /without a delivery ID/,
};

function assertRejected(category, name, run) {
  const pattern = REJECTION[category];
  assert.ok(pattern, `no rejection pattern for category ${category}`);
  assert.throws(run, pattern, `${name} (${category}) was not rejected`);
}

function runVectors(vectors, decode, options = {}) {
  for (const vector of vectors) {
    if (vector.category === undefined) {
      const decoded = decode(bytes(vector.body));
      options.onValid?.(vector, decoded);
    } else {
      assertRejected(vector.category, vector.name, () =>
        decode(bytes(vector.body)),
      );
    }
  }
}

const DESCRIPTOR_CBOR_LIMITS = {
  maxBytes: V2_MAX_ENCRYPTED_DESCRIPTOR_BYTES,
  maxMapPairs: 128,
  maxArrayElements: 4096,
  maxDepth: 8,
  requireDeterministic: true,
};

test('frozen corpus covers every wire shape the release ships', () => {
  for (const section of [
    'chain',
    'lookupIds',
    'enrollmentProofs',
    'proofs',
    'operationIds',
    'descriptors',
    'invalidDescriptors',
    'deliveryFrames',
    'inboxRequests',
    'inboxResponses',
    'completionRequests',
    'controlEventRequests',
  ]) {
    assert.ok(
      Array.isArray(corpus[section]) && corpus[section].length > 0,
      `frozen corpus section ${section} is empty`,
    );
  }
  const payloadTypes = new Set(
    corpus.descriptors.map((vector) => vector.payloadType),
  );
  for (const payloadType of [1, 2, 3, 4, 5, 6]) {
    assert.ok(
      payloadTypes.has(payloadType),
      `no frozen descriptor vector covers payload type ${payloadType}`,
    );
  }
  for (const group of [
    corpus.deliveryFrames,
    corpus.inboxRequests,
    corpus.inboxResponses,
    corpus.completionRequests,
    corpus.controlEventRequests,
    corpus.descriptors,
  ]) {
    assert.ok(
      group.some((vector) => vector.category === undefined),
      'frozen corpus group has no valid vector',
    );
  }
  assert.ok(
    corpus.invalidDescriptors.every((vector) => vector.category !== undefined),
    'invalid descriptor vectors must all name a category',
  );
  // The chain vectors drive the receiver's replay/fork/gap rules on the client;
  // the server never sees them, but the corpus must keep covering every outcome.
  assert.deepEqual(
    new Set(corpus.chain.map((link) => link.outcome)),
    new Set([
      'accept',
      'duplicate',
      'stale',
      'fork',
      'predecessor-fork',
      'gap',
    ]),
  );
  for (const link of corpus.chain) {
    const envelope = decodeCbor(bytes(link.envelope), DESCRIPTOR_CBOR_LIMITS);
    assert.ok(envelope instanceof Map);
    assert.deepEqual([...envelope.keys()], [1, 2]);
    assert.equal(envelope.get(2).byteLength, 64);
    // The signed digest is over the canonical descriptor map alone, so the
    // server's encoder must reproduce it byte for byte from the frozen bytes.
    assert.equal(
      hex(sha256(encodeCbor(envelope.get(1)))),
      link.descriptorDigest,
      `${link.name}: descriptor digest`,
    );
    assert.equal(envelope.get(1).get(10), link.sequence);
  }
});

test('frozen daily capability lookup IDs reproduce on the server', async () => {
  for (const vector of corpus.lookupIds) {
    assert.equal(
      hex(
        await deriveV2DailyCapabilityLookupId(
          bytes(vector.tokenSecret),
          vector.epoch,
        ),
      ),
      vector.lookupId,
      `lookup ID for epoch ${vector.epoch}`,
    );
  }
  const epochs = new Set(corpus.lookupIds.map((vector) => vector.lookupId));
  assert.equal(
    epochs.size,
    corpus.lookupIds.length,
    'daily lookup IDs must differ per epoch',
  );
});

test('frozen enrollment proofs reproduce on the server', async () => {
  // The client computes this proof and the server checks it, so a divergence
  // here would gate a deployment against its own clients. The secret is a typed
  // passphrase, so the stretching step is pinned exactly on both
  // implementations, salt and iteration count included.
  for (const vector of corpus.enrollmentProofs) {
    const key = await deriveV2EnrollmentKey(vector.secret);
    assert.equal(hex(key), vector.key, `enrollment key for ${vector.secret}`);
    assert.equal(
      hex(
        await deriveV2EnrollmentProof(
          key,
          bytes(vector.locator),
          vector.expiresAt,
        ),
      ),
      vector.proof,
      `enrollment proof for ${vector.locator} at ${vector.expiresAt}`,
    );
  }
  // Keyed by everything a proof covers. Two secrets that name the same key are
  // meant to collide here — that is what lets a server configured with the
  // derived key verify a client that still holds the passphrase — so the
  // property is that nothing else does.
  const proofs = new Map(
    corpus.enrollmentProofs.map((vector) => [
      `${vector.key}|${vector.locator}|${vector.expiresAt}`,
      vector.proof,
    ]),
  );
  assert.equal(
    new Set(proofs.values()).size,
    proofs.size,
    'an enrollment proof must differ per key, locator and expiry',
  );
  const passphrase = corpus.enrollmentProofs.find(
    (vector) => vector.secret === 'squid-lantern-rotate-9-mango',
  );
  const derived = corpus.enrollmentProofs.find((vector) =>
    vector.secret.startsWith('dud2-enroll-key:'),
  );
  assert.equal(
    derived.proof,
    passphrase.proof,
    'the derived-key form must reach the same proof as the passphrase it came from',
  );
});

test('the enrollment passphrase is stretched at the agreed work factor', async () => {
  // A captured proof is an offline verifier, so the KDF cost is the control
  // that protects the passphrase. Dropping it would keep every other test
  // passing and both implementations interoperating, so assert it directly
  // rather than only through the frozen corpus.
  assert.ok(
    V2_ENROLLMENT_KDF_ITERATIONS >= 600_000,
    `enrollment KDF work factor dropped to ${V2_ENROLLMENT_KDF_ITERATIONS}`,
  );
  const vector = corpus.enrollmentProofs[0];
  const material = await crypto.subtle.importKey(
    'raw',
    new TextEncoder().encode(vector.secret),
    'PBKDF2',
    false,
    ['deriveBits'],
  );
  const expected = new Uint8Array(
    await crypto.subtle.deriveBits(
      {
        name: 'PBKDF2',
        hash: 'SHA-256',
        salt: new TextEncoder().encode('dud/v2/enrollment-key'),
        iterations: V2_ENROLLMENT_KDF_ITERATIONS,
      },
      material,
      256,
    ),
  );
  assert.equal(hex(expected), vector.key);
});

test('frozen compound proofs verify and stay bound to their request', async () => {
  for (const vector of corpus.proofs) {
    const proof = bytes(vector.proof);
    const rebuilt = await buildV2DeliveryProof({
      tokenSecret: bytes(vector.tokenSecret),
      capabilityLookupId: bytes(vector.lookupId),
      direction: vector.direction,
      scope: vector.scope,
      chain: vector.chain,
      slot: bytes(vector.slot),
      slotEpoch: vector.epoch,
      method: vector.method,
      canonicalOrigin: vector.origin,
      normalizedPath: vector.path,
      operationIndex: vector.operationIndex,
      requestDigest: bytes(vector.requestDigest),
      nonce: bytes(vector.nonce),
      expiresAt: vector.expiresAt,
    });
    assert.equal(hex(rebuilt), vector.proof, `${vector.name}: proof bytes`);

    const parsed = parseV2DeliveryProof(proof);
    assert.deepEqual(parsed.capabilityLookupId, bytes(vector.lookupId));
    assert.deepEqual(parsed.nonce, bytes(vector.nonce));
    assert.equal(parsed.expiresAt, vector.expiresAt);
    assert.equal(parsed.operationIndex, vector.operationIndex);

    const accepted = await verifyV2DeliveryProof({
      tokenSecret: bytes(vector.tokenSecret),
      capabilityLookupId: bytes(vector.lookupId),
      direction: vector.direction,
      scope: vector.scope,
      chain: vector.chain,
      slot: bytes(vector.slot),
      slotEpoch: vector.epoch,
      method: vector.method,
      canonicalOrigin: vector.origin,
      normalizedPath: vector.path,
      requestDigest: bytes(vector.requestDigest),
      proof,
    });
    assert.equal(
      accepted?.operationIndex,
      vector.operationIndex,
      `${vector.name}: proof did not verify`,
    );

    // Each bound field must be load-bearing on its own.
    const base = {
      tokenSecret: bytes(vector.tokenSecret),
      capabilityLookupId: bytes(vector.lookupId),
      direction: vector.direction,
      scope: vector.scope,
      chain: vector.chain,
      slot: bytes(vector.slot),
      slotEpoch: vector.epoch,
      method: vector.method,
      canonicalOrigin: vector.origin,
      normalizedPath: vector.path,
      requestDigest: bytes(vector.requestDigest),
      proof,
    };
    const alteredSlot = Uint8Array.from(base.slot);
    alteredSlot[0] ^= 1;
    const alteredDigest = Uint8Array.from(base.requestDigest);
    alteredDigest[0] ^= 1;
    for (const [field, override] of [
      [
        'direction',
        {
          direction:
            vector.direction === 'inviter->invitee'
              ? 'invitee->inviter'
              : 'inviter->invitee',
        },
      ],
      ['scope', { scope: vector.scope === 'write' ? 'read' : 'write' }],
      ['chain', { chain: vector.chain === 0 ? 1 : 0 }],
      ['slot', { slot: alteredSlot }],
      ['slotEpoch', { slotEpoch: vector.epoch + 1 }],
      ['method', { method: 'GET' }],
      ['canonicalOrigin', { canonicalOrigin: 'https://other.example.com' }],
      ['normalizedPath', { normalizedPath: `${vector.path}/other` }],
      ['requestDigest', { requestDigest: alteredDigest }],
    ]) {
      assert.equal(
        await verifyV2DeliveryProof({ ...base, ...override }),
        null,
        `${vector.name}: proof is not bound to ${field}`,
      );
    }
  }
});

test('frozen operation IDs are exactly sixteen opaque bytes', () => {
  for (const operationId of corpus.operationIds) {
    assert.equal(bytes(operationId).byteLength, 16);
  }
  assert.equal(
    new Set(corpus.operationIds).size,
    corpus.operationIds.length,
    'operation ID vectors must be distinct',
  );
});

test('frozen descriptor maps are deterministic CBOR with matching digests', () => {
  let crossChecked = 0;
  for (const vector of corpus.descriptors) {
    const descriptor = bytes(vector.descriptor);
    assert.equal(
      hex(sha256(descriptor)),
      vector.descriptorDigest,
      `${vector.name}: descriptor digest`,
    );
    assert.equal(bytes(vector.signature).byteLength, 64);
    if (vector.textKeyedMaps) {
      // Git ref maps are the one protocol structure with text keys; the
      // server's integer-key protocol codec cannot parse them, and never has
      // to, since a descriptor reaches it as opaque ciphertext.
      assert.throws(
        () => decodeCbor(descriptor, DESCRIPTOR_CBOR_LIMITS),
        /not an unsigned integer/,
      );
      continue;
    }
    crossChecked += 1;
    // Both implementations must agree the signed bytes are canonical.
    const decoded = decodeCbor(descriptor, DESCRIPTOR_CBOR_LIMITS);
    assert.ok(
      decoded instanceof Map,
      `${vector.name}: descriptor is not a map`,
    );
    assert.deepEqual(
      encodeCbor(decoded),
      descriptor,
      `${vector.name}: descriptor is not canonical for the server encoder`,
    );

    const envelope = decodeCbor(bytes(vector.envelope), DESCRIPTOR_CBOR_LIMITS);
    assert.ok(envelope instanceof Map);
    assert.deepEqual([...envelope.keys()], [1, 2]);
    assert.deepEqual(envelope.get(2), bytes(vector.signature));
    assert.equal(decoded.get(1), 2, `${vector.name}: protocol version`);
    assert.equal(decoded.get(9), 0, `${vector.name}: key epoch`);
    assert.equal(decoded.get(5), vector.payloadType);
    // Chain and payload type must agree: 1-4 on data, 5-6 on control.
    assert.equal(decoded.get(8), vector.payloadType <= 4 ? 0 : 1);
    for (const deferred of [24, 25, 26]) {
      assert.equal(
        decoded.has(deferred),
        false,
        `${vector.name}: deferred key ${deferred} present`,
      );
    }
  }
  assert.ok(crossChecked >= 5, 'too few descriptors cross-checked');
});

test('frozen invalid descriptor envelopes are well-formed but never valid', () => {
  const nonDeterministic = corpus.invalidDescriptors.filter(
    (vector) => vector.category === 'non-deterministic-envelope',
  );
  assert.ok(nonDeterministic.length > 0);
  for (const vector of nonDeterministic) {
    assert.throws(
      () => decodeCbor(bytes(vector.envelope), DESCRIPTOR_CBOR_LIMITS),
      /deterministic|ascending|order|sorted/,
      `${vector.name}: server CBOR decoder accepted a non-canonical envelope`,
    );
  }
  // Every other invalid descriptor is a well-formed two-key envelope whose
  // defect is semantic and therefore the client's to reject; the bytes must
  // still parse here so both suites are provably testing the same corpus.
  for (const vector of corpus.invalidDescriptors) {
    if (vector.category === 'non-deterministic-envelope') {
      continue;
    }
    const envelope = bytes(vector.envelope);
    assert.equal(
      envelope[0],
      0xa2,
      `${vector.name}: envelope is not a two-entry CBOR map`,
    );
    if (vector.textKeyedMaps) {
      continue;
    }
    const decoded = decodeCbor(envelope, DESCRIPTOR_CBOR_LIMITS);
    assert.ok(decoded instanceof Map, `${vector.name}: envelope is not a map`);
    assert.deepEqual([...decoded.keys()], [1, 2]);
  }
});

test('frozen delivery frames decode exactly as the client encoded them', () => {
  let valid = 0;
  runVectors(corpus.deliveryFrames, decodeV2DeliveryRequestFrame, {
    onValid: (vector, decoded) => {
      valid += 1;
      assert.equal(
        decoded.header.get(V2_DELIVERY_REQUEST_KEYS.payloadLength),
        decoded.payload.byteLength,
        `${vector.name}: payload length`,
      );
      assert.deepEqual(
        decoded.header.get(V2_DELIVERY_REQUEST_KEYS.payloadDigest),
        sha256(decoded.payload),
        `${vector.name}: payload digest`,
      );
      assert.equal(
        decoded.header.get(V2_DELIVERY_REQUEST_KEYS.operationId).byteLength,
        16,
      );
      // Re-framing the decoded header must reproduce the frozen bytes.
      assert.deepEqual(
        encodeV2DeliveryFrame(
          decoded.header,
          decoded.payload,
          V2_DELIVERY_REQUEST_KEYS.payloadLength,
          V2_DELIVERY_REQUEST_KEYS.payloadDigest,
        ),
        bytes(vector.body),
        `${vector.name}: re-encoding is not byte-identical`,
      );
      // The authorization digest must be stable and MAC-independent.
      const digest = v2DeliveryFrameAuthorizationDigest(bytes(vector.body));
      assert.equal(digest.byteLength, 32);
    },
  });
  assert.ok(valid >= 4, 'expected several valid delivery-frame vectors');
});

test('frozen inbox requests decode and digest identically on the server', () => {
  runVectors(corpus.inboxRequests, (body) => decodeV2InboxRequest(body), {
    onValid: (vector, decoded) => {
      const proofs = decoded.header.get(V2_INBOX_REQUEST_KEYS.dataSlotProofs);
      assert.ok(Array.isArray(proofs) && proofs.length > 0);
      assert.ok(proofs.length <= V2_MAX_BATCHED_SLOT_PROOFS);
      assert.deepEqual(
        encodeCbor(decoded.header),
        bytes(vector.body),
        `${vector.name}: re-encoding is not byte-identical`,
      );
      assert.equal(
        v2InboxRequestAuthorizationDigest(bytes(vector.body)).byteLength,
        32,
      );
    },
  });
});

test('frozen inbox responses decode under the server response contract', () => {
  runVectors(corpus.inboxResponses, decodeV2InboxResponseFrame, {
    onValid: (vector, decoded) => {
      assert.deepEqual(
        encodeV2DeliveryFrame(decoded.header, decoded.payload, 7, 8),
        bytes(vector.body),
        `${vector.name}: re-encoding is not byte-identical`,
      );
    },
  });
});

test('frozen completion requests decode and redact their two proof MACs', () => {
  runVectors(corpus.completionRequests, decodeV2CompletionRequest, {
    onValid: (vector, decoded) => {
      assert.equal(
        decoded.header.get(V2_COMPLETION_REQUEST_KEYS.deliveryId).byteLength,
        16,
      );
      assert.ok(
        [0, 1].includes(decoded.header.get(V2_COMPLETION_REQUEST_KEYS.result)),
      );
      assert.deepEqual(
        encodeCbor(decoded.header),
        bytes(vector.body),
        `${vector.name}: re-encoding is not byte-identical`,
      );
      assert.equal(
        v2CompletionRequestAuthorizationDigest(bytes(vector.body)).byteLength,
        32,
      );
    },
  });
});

test('frozen inline control envelopes decode under the server contract', () => {
  runVectors(corpus.controlEventRequests, decodeV2ControlEventRequest, {
    onValid: (vector, decoded) => {
      assert.equal(
        decoded.header.get(V2_CONTROL_EVENT_REQUEST_KEYS.operationId)
          .byteLength,
        16,
      );
      assert.deepEqual(
        encodeCbor(decoded.header),
        bytes(vector.body),
        `${vector.name}: re-encoding is not byte-identical`,
      );
      assert.equal(
        v2ControlEventRequestAuthorizationDigest(bytes(vector.body)).byteLength,
        32,
      );
    },
  });
});

/**
 * Re-verifies a proof the client embedded in a frozen body. The MAC covers the
 * request digest the client computed over its own MAC-redacted encoding, so
 * this passes only when both implementations redact byte-identically.
 */
async function assertEmbeddedProofVerifies(
  vector,
  slotProof,
  scope,
  path,
  digest,
  label,
) {
  const parsed = parseV2DeliveryProof(slotProof.get(4));
  const accepted = await verifyV2DeliveryProof({
    tokenSecret: bytes(vector.tokenSecret),
    capabilityLookupId: parsed.capabilityLookupId,
    direction: vector.direction,
    scope,
    chain: slotProof.get(3),
    slot: slotProof.get(1),
    slotEpoch: slotProof.get(2),
    method: 'POST',
    canonicalOrigin: vector.origin,
    normalizedPath: path,
    requestDigest: digest,
    proof: slotProof.get(4),
  });
  assert.ok(
    accepted,
    `${vector.name}: ${label} proof did not verify against the server's redaction`,
  );
  assert.equal(
    hex(parsed.capabilityLookupId),
    hex(
      await deriveV2DailyCapabilityLookupId(
        bytes(vector.tokenSecret),
        slotProof.get(2),
      ),
    ),
    `${vector.name}: ${label} proof names the wrong daily lookup ID`,
  );
}

test('server redaction reproduces every proof the client embedded', async () => {
  let verified = 0;

  for (const vector of corpus.deliveryFrames) {
    if (vector.category !== undefined) {
      continue;
    }
    const frame = bytes(vector.body);
    const { header } = decodeV2DeliveryRequestFrame(frame);
    const digest = v2DeliveryFrameAuthorizationDigest(frame);
    await assertEmbeddedProofVerifies(
      vector,
      header.get(V2_DELIVERY_REQUEST_KEYS.dataSlotProof),
      'write',
      '/v2/deliveries',
      digest,
      'data slot',
    );
    verified += 1;
    for (const query of header.get(V2_DELIVERY_REQUEST_KEYS.controlQueries) ??
      []) {
      await assertEmbeddedProofVerifies(
        vector,
        query,
        'read',
        '/v2/deliveries',
        digest,
        'control query',
      );
      verified += 1;
    }
  }

  for (const vector of corpus.inboxRequests) {
    if (vector.category !== undefined) {
      continue;
    }
    const body = bytes(vector.body);
    const { header } = decodeV2InboxRequest(body);
    const digest = v2InboxRequestAuthorizationDigest(body);
    for (const key of [
      V2_INBOX_REQUEST_KEYS.dataSlotProofs,
      V2_INBOX_REQUEST_KEYS.controlSlotProofs,
    ]) {
      for (const proof of header.get(key) ?? []) {
        await assertEmbeddedProofVerifies(
          vector,
          proof,
          'read',
          '/v2/inbox',
          digest,
          'inbox',
        );
        verified += 1;
      }
    }
  }

  for (const vector of corpus.completionRequests) {
    if (vector.category !== undefined) {
      continue;
    }
    const body = bytes(vector.body);
    const { header } = decodeV2CompletionRequest(body);
    const digest = v2CompletionRequestAuthorizationDigest(body);
    const path = `/v2/deliveries/${hex(
      header.get(V2_COMPLETION_REQUEST_KEYS.deliveryId),
    )}/complete`;
    await assertEmbeddedProofVerifies(
      vector,
      header.get(V2_COMPLETION_REQUEST_KEYS.dataAckProof),
      'ack',
      path,
      digest,
      'acknowledgement',
    );
    await assertEmbeddedProofVerifies(
      vector,
      header.get(V2_COMPLETION_REQUEST_KEYS.controlWriteProof),
      'write',
      path,
      digest,
      'control write',
    );
    verified += 2;
  }

  for (const vector of corpus.controlEventRequests) {
    if (vector.category !== undefined) {
      continue;
    }
    const body = bytes(vector.body);
    const { header } = decodeV2ControlEventRequest(body);
    await assertEmbeddedProofVerifies(
      vector,
      header.get(V2_CONTROL_EVENT_REQUEST_KEYS.controlSlotProof),
      'write',
      '/v2/control-events',
      v2ControlEventRequestAuthorizationDigest(body),
      'inline control',
    );
    verified += 1;
  }

  assert.ok(verified >= 40, `only ${verified} embedded proofs were verified`);
});

test('frozen proofs bind their position, nonce and expiry', async () => {
  const positions = {
    deliveryFrames: (body) => {
      const header = decodeV2DeliveryRequestFrame(body).header;
      return [
        header.get(V2_DELIVERY_REQUEST_KEYS.dataSlotProof),
        ...(header.get(V2_DELIVERY_REQUEST_KEYS.controlQueries) ?? []),
      ];
    },
    inboxRequests: (body) => {
      const header = decodeV2InboxRequest(body).header;
      return [
        ...(header.get(V2_INBOX_REQUEST_KEYS.dataSlotProofs) ?? []),
        ...(header.get(V2_INBOX_REQUEST_KEYS.controlSlotProofs) ?? []),
      ];
    },
    completionRequests: (body) => {
      const header = decodeV2CompletionRequest(body).header;
      return [
        header.get(V2_COMPLETION_REQUEST_KEYS.dataAckProof),
        header.get(V2_COMPLETION_REQUEST_KEYS.controlWriteProof),
      ];
    },
    controlEventRequests: (body) => [
      decodeV2ControlEventRequest(body).header.get(
        V2_CONTROL_EVENT_REQUEST_KEYS.controlSlotProof,
      ),
    ],
  };
  for (const [section, extract] of Object.entries(positions)) {
    for (const vector of corpus[section]) {
      if (vector.category !== undefined) {
        continue;
      }
      const slotProofs = extract(bytes(vector.body));
      for (const [index, slotProof] of slotProofs.entries()) {
        const proof = slotProof.get(4);
        const parsed = parseV2DeliveryProof(proof);
        // The server rejects any proof whose index does not match its position
        // in the request, which is what stops proofs being reordered.
        assert.equal(
          parsed.operationIndex,
          index,
          `${section}/${vector.name}: proof ${index} claims index ${parsed.operationIndex}`,
        );
        assert.equal(parsed.nonce.byteLength, 16);
        assert.ok(parsed.expiresAt > 0);

        // Rewriting the declared expiry or nonce inside the proof must break
        // the MAC, so neither can be extended or replayed independently.
        const decoded = decodeCbor(proof, {
          maxBytes: 160,
          maxMapPairs: 5,
          maxDepth: 2,
          requireDeterministic: true,
        });
        const verifyInput = {
          tokenSecret: bytes(vector.tokenSecret),
          capabilityLookupId: parsed.capabilityLookupId,
          direction: vector.direction,
          scope: 'write',
          chain: slotProof.get(3),
          slot: slotProof.get(1),
          slotEpoch: slotProof.get(2),
          method: 'POST',
          canonicalOrigin: vector.origin,
          normalizedPath: '/v2/deliveries',
          requestDigest: new Uint8Array(32),
        };
        for (const [key, replacement] of [
          [3, parsed.expiresAt + 1],
          [2, new Uint8Array(16)],
        ]) {
          const altered = new Map(decoded);
          altered.set(key, replacement);
          assert.equal(
            await verifyV2DeliveryProof({
              ...verifyInput,
              proof: encodeCbor(altered),
            }),
            null,
            `${section}/${vector.name}: proof field ${key} is not bound by the MAC`,
          );
        }
      }
    }
  }
});

test('a spliced proof from another frozen request never verifies', async () => {
  const [first, second] = corpus.deliveryFrames.filter(
    (vector) => vector.category === undefined,
  );
  const donor = decodeV2DeliveryRequestFrame(bytes(second.body)).header.get(
    V2_DELIVERY_REQUEST_KEYS.dataSlotProof,
  );
  const target = decodeV2DeliveryRequestFrame(bytes(first.body));
  const spliced = new Map(target.header);
  spliced.set(V2_DELIVERY_REQUEST_KEYS.dataSlotProof, donor);
  const frame = encodeV2DeliveryFrame(
    spliced,
    target.payload,
    V2_DELIVERY_REQUEST_KEYS.payloadLength,
    V2_DELIVERY_REQUEST_KEYS.payloadDigest,
  );
  const parsed = parseV2DeliveryProof(donor.get(4));
  assert.equal(
    await verifyV2DeliveryProof({
      tokenSecret: bytes(first.tokenSecret),
      capabilityLookupId: parsed.capabilityLookupId,
      direction: first.direction,
      scope: 'write',
      chain: donor.get(3),
      slot: donor.get(1),
      slotEpoch: donor.get(2),
      method: 'POST',
      canonicalOrigin: first.origin,
      normalizedPath: '/v2/deliveries',
      requestDigest: v2DeliveryFrameAuthorizationDigest(frame),
      proof: donor.get(4),
    }),
    null,
    'a proof lifted from another request verified against this one',
  );
});

test('boundary sizes too large to freeze are still enforced', () => {
  const payload = Uint8Array.of(1);
  const header = (descriptor) =>
    new Map([
      [V2_DELIVERY_REQUEST_KEYS.operationId, new Uint8Array(16)],
      [V2_DELIVERY_REQUEST_KEYS.encryptedDescriptor, descriptor],
      [V2_DELIVERY_REQUEST_KEYS.requestedPolicy, new Map([[1, 1]])],
      [V2_DELIVERY_REQUEST_KEYS.payloadLength, payload.byteLength],
      [V2_DELIVERY_REQUEST_KEYS.payloadDigest, sha256(payload)],
      [
        V2_DELIVERY_REQUEST_KEYS.dataSlotProof,
        new Map([
          [1, new Uint8Array(16)],
          [2, 20_340],
          [3, 0],
          [4, Uint8Array.of(1)],
        ]),
      ],
    ]);
  // One byte past the descriptor limit must be refused; the limit itself is
  // refused only because the surrounding header pushes the frame over.
  assert.throws(
    () =>
      encodeV2DeliveryFrame(
        header(new Uint8Array(V2_MAX_ENCRYPTED_DESCRIPTOR_BYTES + 1)),
        payload,
        V2_DELIVERY_REQUEST_KEYS.payloadLength,
        V2_DELIVERY_REQUEST_KEYS.payloadDigest,
      ),
    /configured limit/,
  );
  // An empty descriptor is equally invalid at the other boundary.
  const emptyDescriptor = encodeV2DeliveryFrame(
    header(new Uint8Array()),
    payload,
    V2_DELIVERY_REQUEST_KEYS.payloadLength,
    V2_DELIVERY_REQUEST_KEYS.payloadDigest,
  );
  assert.throws(
    () => decodeV2DeliveryRequestFrame(emptyDescriptor),
    /configured limit/,
  );
  // A single-byte descriptor is the smallest legal value.
  assert.doesNotThrow(() =>
    decodeV2DeliveryRequestFrame(
      encodeV2DeliveryFrame(
        header(Uint8Array.of(0xa0)),
        payload,
        V2_DELIVERY_REQUEST_KEYS.payloadLength,
        V2_DELIVERY_REQUEST_KEYS.payloadDigest,
      ),
    ),
  );
});
